export * from '@/pages/dashboard/home'
export * from '@/pages/dashboard/testimonial'
export * from '@/pages/dashboard/products'
export * from '@/pages/dashboard/charges'
export * from '@/pages/dashboard/order'
export * from '@/pages/dashboard/settings'
export * from '@/pages/dashboard/blog'
export * from '@/pages/dashboard/help'
export * from '@/pages/dashboard/influencer'
export * from '@/pages/dashboard/style'
export * from '@/pages/dashboard/combination'
export * from '@/pages/dashboard/review'
export * from '@/pages/dashboard/category'

export * from '@/pages/dashboard/subcategory'

